spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=soham
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:7e9d9b8c0a3f4d9f2e3b1a6c5f8e7d2c4b9a1f3e6d8c2a5f7b4e1d9c3a6f8b2}
jwt.expiration=300000